version: "3.7"
services:
    rustfs:
        hostname: rustfs
        image: rustfs/rustfs:1.0.0-alpha.81
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            - RUSTFS_ACCESS_KEY=rustfsadmin
            - RUSTFS_SECRET_KEY=rustfspassword
            - RUSTFS_VOLUMES=/data
            - RUSTFS_ADDRESS=:9000
            - RUSTFS_CONSOLE_ENABLE=true
            - RUSTFS_CONSOLE_ADDRESS=:9001
        healthcheck:
            test: ["CMD-SHELL", "curl --fail http://127.0.0.1:9000/health && curl --fail http://127.0.0.1:9001/rustfs/console/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
networks:
    my-proxy-net:
        external:
            name: custom_network