version: "3.7"
services:
  spark-history-server:
  # docker run --network custom_network -it hadooptest:latest /bin/sh
  # before start: hdfs dfs -mkdir /spark-logs
    build:
      context: .
    image: spark
    command: java -cp "/spark-2.4.0-bin-hadoop2.7/conf/:/spark-2.4.0-bin-hadoop2.7/jars/*" org.apache.spark.deploy.history.HistoryServer
    environment:
    - SPARK_HOME=/spark-2.4.0-bin-hadoop2.7
    - SPARK_CONF_DIR=/spark-2.4.0-bin-hadoop2.7/conf/
    ports:
    - "18080:18080"
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: custom_network