version: "3.7"
services:
  spark-master:
    image: spark
    ports:
    - "8080:8080"
    - "7077:7077"
    command: java -cp "/spark-2.4.0-bin-hadoop2.7/conf/:/spark-2.4.0-bin-hadoop2.7/jars/*" org.apache.spark.deploy.master.Master -h master
    hostname: master
    volumes:
      - applications2:/applications
    
  spark-worker-1:
    image: spark
    command: java -cp "/spark-2.4.0-bin-hadoop2.7/conf/:/spark-2.4.0-bin-hadoop2.7/jars/*" org.apache.spark.deploy.worker.Worker spark-master:7077
    ports:
    - "8081:8081"
    volumes:
      - applications2:/applications

volumes:
  applications2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/jsicotte/Documents/workspaces/spark/applications