version: '3'

services:
    prometheus:
      image: prom/prometheus:v2.1.0
      ports:
      - 9090:9090
    grafana:
      image: grafana/grafana:7.0.5-ubuntu
      ports:
      - 3000:3000


networks:
  my-proxy-net:
    external:
      name: custom_network