version: '3'

services:
    jupyter-hadoop:
        build:
            context: jupyter
        ports:
        - 8888:8888
        environment:
        - HADOOP_HOME=/home/jovyan/work
        volumes:
        #- hdfs_hadoop:/hadoop-2.7.6
        - spark_spark:/spark-2.4.0-bin-hadoop2.7
        environment:
        - HADOOP_HOME=/hadoop-2.7.6
        - SPARK_HOME=/spark-2.4.0-bin-hadoop2.7
        - HADOOP_CONF_DIR=/hadoop-2.7.6/etc/hadoop
        - YARN_CONF_DIR=/hadoop-2.7.6/etc/hadoop
        networks:
        - my-proxy-net
    jupyter:
        image: jupyter/all-spark-notebook
        ports:
        - 8888:8888
        volumes:
        - .:/home/jovyan/work
    nteract:
        build:
            context: nteract
        ports:
        - 8889:8888
        volumes:
        - .:/home/jovyan/work
        command: ["jupyter", "nteract"]
    commuter:
        build:
            context: ./commuter
        ports:
        - 4000:4000
        command: ["exec", "commuter"]
        volumes:
        - .:/home/jovyan/work
        environment:
        - COMMUTER_LOCAL_STORAGE_BASEDIRECTORY=/home/jovyan/work
volumes:
    hdfs_hadoop:
        external: true
    spark_spark:
        external: true

networks:
  my-proxy-net:
    external:
      name: custom_network
