version: '3'

services:
    jupyter-hadoop:
        build:
            context: jupyter
        command: ["jupyter", "lab", "--ip", "0.0.0.0", "--allow-root"]
        ports:
        - 8888:8888
        - 45560:45560
        environment:
        - HADOOP_HOME=/home/jovyan/work
        # volumes:
        #- hdfs_hadoop:/hadoop-2.7.6
        # - spark_spark:/spark-2.4.0-bin-hadoop2.7
        environment:
        - HADOOP_HOME=/hadoop-2.7.6
        - SPARK_HOME=/spark-2.4.0-bin-hadoop2.7
        - HADOOP_CONF_DIR=/hadoop-2.7.6/etc/hadoop
        - YARN_CONF_DIR=/hadoop-2.7.6/etc/hadoop
        - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64/jre
        networks:
        - my-proxy-net
    nteract:
        build:
            context: nteract
        ports:
        - 8889:8888
        volumes:
        - .:/home/jovyan/work
        command: ["jupyter", "nteract"]
    commuter:
        build:
            context: ./commuter
        ports:
        - 4000:4000
        command: ["exec", "commuter"]
        volumes:
        - .:/home/jovyan/work
        environment:
        - COMMUTER_LOCAL_STORAGE_BASEDIRECTORY=/home/jovyan/work

networks:
  my-proxy-net:
    external:
      name: custom_network
