apiVersion: apps/v1
kind: Deployment
metadata:
  name: overlord
  labels:
    {{- include "druid.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: overlord
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: overlord
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: overlord
          image: apache/druid:24.0.0
          imagePullPolicy: IfNotPresent
          args: [ "overlord" ]
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: druid-config