version: "3.7"
services:
    minio:
        hostname: minio
        image: docker.io/minio/minio
        ports:
            - 9003:9003
        environment:
            - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        command: minio server /home/shared --console-address :9003
        labels:
            - traefik.http.routers.my-container.rule=Host(`minio.mysite.test`)