version: "3.7"
services:
    minio:
        hostname: minio
        image: minio/minio
        ports:
            - 9000:9000
        environment:
            - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        command: server /data
networks:
    my-proxy-net:
        external:
            name: custom_network