apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    {{- include "druid.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.5
          imagePullPolicy: IfNotPresent
          env:
            - name: ZOO_MY_ID
              value: '1'
